version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: mssql
    ports:
      - 1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ThisIsReallyStrongPassword123
      MSSQL_PID: Developer
    volumes:
      - ./database:/var/opt/mssql/data
  api:
    image: ryuichi24/onlineshopapi
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    container_name: api
    ports:
      - 2000
  client:
    image: ryuichi24/onlineshopclient
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - API_URL=/api
    restart: always
    container_name: client
    ports:
      - 8000:80
    volumes:
      - ./client/nginx:/etc/nginx/conf.d
